
# Instead of using the column types below while loading epa tables, all epa table columns are initially
# varchar. This is because missing values are represented by empty quotes regarless of data type, which
# causes psql copy to fail. After tables are loaded into the DB, columns are cast to the appropriate type.

class prop: pass
prop.colTypeMap = {
    'state_code'                   : 'varchar',
    'county_code'                  : 'varchar',
    'site_num'                     : 'varchar',
    'site_number'                  : 'varchar',    
    'parameter_code'               : 'varchar',
    'poc'                          : 'varchar',
    'parameter_name'               : 'varchar',
    'sample_duration'              : 'varchar',
    'pollutant_standard'           : 'varchar',
    'metric_used'                  : 'varchar',
    'method_name'                  : 'varchar',
    'method_code'                  : 'varchar',    
    'year'                         : 'integer',
    'units_of_measure'             : 'varchar',
    'event_type'                   : 'varchar',
    'observation_count'            : 'integer',
    'observation_percent'          : 'numeric',
    'completeness_indicator'       : 'varchar',
    'valid_day_count'              : 'integer',
    'required_day_count'           : 'integer',
    'exceptional_data_count'       : 'integer',
    'null_data_count'              : 'integer',
    'primary_exceedance_count'     : 'integer',
    'secondary_exceedance_count'   : 'integer',
    'certification_indicator'      : 'varchar',
    'num_obs_below_mdl'            : 'integer',
    'arithmetic_mean'              : 'numeric',
    'arithmetic_standard_dev'      : 'numeric',
    'first_max_value'              : 'numeric',
    'first_max_hour'               : 'integer',
    'first_max_datetime'           : 'timestamp',
    'second_max_value'             : 'numeric',
    'second_max_datetime'          : 'timestamp',
    'third_max_value'              : 'numeric',
    'third_max_datetime'           : 'timestamp',    
    'fourth_max_value'             : 'numeric',
    'fourth_max_datetime'          : 'timestamp',
    'first_max_non_overlapping_value'  : 'numeric',
    'first_no_max_datetime'            : 'timestamp',
    'second_max_non_overlapping_value' : 'numeric',
    'second_no_max_datetime'           : 'timestamp',
    'ninetyninth_percentile'       : 'numeric',
    'ninetyeighth_percentile'      : 'numeric',
    'ninetyfifth_percentile'       : 'numeric',
    'ninetieth_percentile'         : 'numeric',
    'seventyfifth_percentile'      : 'numeric',
    'fiftieth_percentile'          : 'numeric',
    'tenth_percentile'             : 'numeric',
    'local_site_name'              : 'varchar',
    'address'                      : 'varchar',
    'state_name'                   : 'varchar',
    'county_name'                  : 'varchar',
    'city_name'                    : 'varchar',
    'cbsa_name'                    : 'varchar',
    'date_of_last_change'          : 'date',
    'latitude'                     : 'numeric',
    'longitude'                    : 'numeric',
    'datum'                        : 'varchar',
    'date_local'                   : 'date',
    'time_local'                   : 'time',
    'date_gmt'                     : 'date',
    'time_gmt'                     : 'time',
    'observations_with_events'     : 'integer',
    'null_observations'            : 'integer',
    'mean_including_all_data'      : 'numeric',
    'mean_excluding_all_flagged_data' : 'numeric',
    'mean_excluding_concurred_flags'  : 'numeric',
    'aqi'                          : 'integer',
    'elevation'                    : 'numeric',
    'land_use'                     : 'varchar',
    'location_setting'             : 'varchar',
    'site_established_date'        : 'date',
    'site_closed_date'             : 'date',
    'met_site_state_code'          : 'varchar',
    'met_site_county_code'         : 'varchar',
    'met_site_site_number'         : 'varchar',
    'met_site_type'                : 'varchar',
    'met_site_distance'            : 'numeric',
    'met_site_direction'           : 'varchar',
    'gmt_offset'                   : 'integer',
    'owning_agency'                : 'varchar',
    'zip_code'                     : 'varchar',
    'tribe_name'                   : 'varchar',
    'extraction_date'              : 'date'
}

class annual: pass
prop.annual = annual
annual.colNames_orig = [
    'state_code',
    'county_code',
    'site_num',
    'parameter_code',
    'poc',
    'latitude',
    'longitude',
    'datum',
    'parameter_name',
    'sample_duration',
    'pollutant_standard',
    'metric_used',
    'method_name',
    'year',
    'units_of_measure',
    'event_type',
    'observation_count',
    'observation_percent',
    'completeness_indicator',
    'valid_day_count',
    'required_day_count',
    'exceptional_data_count',
    'null_data_count',
    'primary_exceedance_count',
    'secondary_exceedance_count',
    'certification_indicator',
    'num_obs_below_mdl',
    'arithmetic_mean',
    'arithmetic_standard_dev',
    'first_max_value',
    'first_max_datetime',
    'second_max_value',
    'second_max_datetime',
    'third_max_value',
    'third_max_datetime',
    'fourth_max_value',
    'fourth_max_datetime',
    'first_max_non_overlapping_value',
    'first_no_max_datetime',
    'second_max_non_overlapping_value',
    'second_no_max_datetime',
    'ninetyninth_percentile',
    'ninetyeighth_percentile',
    'ninetyfifth_percentile',
    'ninetieth_percentile',
    'seventyfifth_percentile',
    'fiftieth_percentile',
    'tenth_percentile',
    'local_site_name',
    'address',
    'state_name',
    'county_name',
    'city_name',
    'cbsa_name',
    'date_of_last_change'
]

prop.annual.headerLine = '"State Code","County Code","Site Num","Parameter Code","POC","Latitude","Longitude","Datum","Parameter Name","Sample Duration","Pollutant Standard","Metric Used","Method Name","Year","Units of Measure","Event Type","Observation Count","Observation Percent","Completeness Indicator","Valid Day Count","Required Day Count","Exceptional Data Count","Null Data Count","Primary Exceedance Count","Secondary Exceedance Count","Certification Indicator","Num Obs Below MDL","Arithmetic Mean","Arithmetic Standard Dev","1st Max Value","1st Max DateTime","2nd Max Value","2nd Max DateTime","3rd Max Value","3rd Max DateTime","4th Max Value","4th Max DateTime","1st Max Non Overlapping Value","1st NO Max DateTime","2nd Max Non Overlapping Value","2nd NO Max DateTime","99th Percentile","98th Percentile","95th Percentile","90th Percentile","75th Percentile","50th Percentile","10th Percentile","Local Site Name","Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"'

class daily: pass
prop.daily = daily
prop.daily.colNames_orig = [
    'state_code',
    'county_code',
    'site_num',
    'parameter_code',
    'poc',
    'latitude',
    'longitude',
    'datum',
    'parameter_name',
    'sample_duration',
    'pollutant_standard',
    'date_local',
    'units_of_measure',
    'event_type',
    'observation_count',
    'observation_percent',
    'arithmetic_mean',
    'first_max_value',
    'first_max_hour',
    'aqi',
    'method_code',
    'method_name',
    'local_site_name',
    'address',
    'state_name',
    'county_name',
    'city_name',
    'cbsa_name',
    'date_of_last_change']

prop.daily.headerLine = '"State Code","County Code","Site Num","Parameter Code","POC","Latitude","Longitude","Datum","Parameter Name","Sample Duration","Pollutant Standard","Date Local","Units of Measure","Event Type","Observation Count","Observation Percent","Arithmetic Mean","1st Max Value","1st Max Hour","AQI","Method Code","Method Name","Local Site Name","Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"'

class eight_hour: pass
prop.eight_hour = eight_hour
prop.eight_hour.colNames_orig = [
    'state_code',
    'county_code',
    'site_num',
    'parameter_code',
    'poc',
    'latitude',
    'longitude',
    'datum',
    'parameter_name',
    'date_local',
    'time_local',
    'date_gmt',
    'time_gmt',
    'sample_duration',
    'pollutant_standard',
    'units_of_measure',
    'observation_count',
    'observations_with_events',
    'null_observations',
    'mean_including_all_data',
    'mean_excluding_all_flagged_data',
    'mean_excluding_concurred_flags',
    'date_of_last_change']

prop.eight_hour.headerLine = '"State Code","County Code","Site Num","Parameter Code","POC","Latitude","Longitude","Datum","Parameter Name","Date Local","Time Local","Date GMT","Time GMT","Sample Duration","Pollutant Standard","Units of Measure","Observation Count","Observations with Events","Null Observations","Mean Including All Data","Mean Excluding All Flagged Data","Mean Excluding Concurred Flags","Date of Last Change"'

class sites: pass
prop.sites = sites
prop.sites.colNames_orig = [
    'state_code',
    'county_code',
    'site_number',
    'latitude',
    'longitude',
    'datum',
    'elevation',
    'land_use',
    'location_setting',
    'site_established_date',
    'site_closed_date',
    'met_site_state_code',
    'met_site_county_code',
    'met_site_site_number',
    'met_site_type',
    'met_site_distance',
    'met_site_direction',
    'gmt_offset',
    'owning_agency',
    'local_site_name',
    'address',
    'zip_code',
    'state_name',
    'county_name',
    'city_name',
    'cbsa_name',
    'tribe_name',
    'extraction_date'
]
